prometeo/altmed/altmed/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from core import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^core/',include('core.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

prometeo/altmed/core/urls.py
from django.conf.urls import url
from core import views# SET THE NAMESPACE!
app_name = 'core'# Be careful setting the name to just /login use userlogin instead!

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^headache/$',views.headache1,name='headache'),
    url(r'^malaria/$',views.malaria1,name='malaria'),
]

prometeo/altmed/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    doctorName= models.CharField(max_length=200,null =True)
    doctorId = models.CharField(unique=True,max_length=200,null=True)
    hospitalName=models.CharField(max_length=200,null=True)
    # isApproved=models.BooleanField(default=False)
    isApproved=models.IntegerField(default=0)

    def __str__(self):
        return self.doctorName


class headache(models.Model):
    name=models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.name

class malaria(models.Model):
    name=models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.name

prometeo/altmed/core/forms.py
from django import forms
from core.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('doctorName','doctorId','hospitalName')

prometeo/altmed/core/views.py
from django.shortcuts import render
from .models import UserProfileInfo,headache,malaria
from .forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user and UserProfileInfo.isApproved!=0:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
                # return render(request,'badlogin.html')
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            # return HttpResponse("Invalid login details given")
            return render(request,'badlogin.html')
    else:
        return render(request, 'login.html', {})




def malaria1(request):
    a=malaria.objects.all()
    if request.method=='POST':
        add=request.POST.get('add')
        d=malaria(name=add)
        d.save()
        a=malaria.objects.all()
        return render(request,'malaria.html',{'medicine':a})
    else:
        return render(request,'malaria.html',{'medicine':a})

def headache1(request):
    a=headache.objects.all()
    if request.method=='POST':
        add=request.POST.get('add')
        d=headache(name=add)
        d.save()
        a=headache.objects.all()
        return render(request,'headache.html',{'medicine':a})
    else:
        return render(request,'headache.html',{'medicine':a})

prometeo/altmed/templates/badlogin.html
{% extends "base.html" %}
{% block body_block %}<div class="container">
  <div class="jumbotron">
    <h3>Invalid user login details or Your account has not been approved by the admin yet</h3>
    </div>
</div>{% endblock %}

prometeo/altmed/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"></head>
  <body>
    <style media="screen">
    body {
background-color: #009e73;
}
    </style>
    <nav class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <ul class="nav navbar-nav">{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">AltMeds</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'core:register' %}">Doctor Registration</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'core:user_login' %}">Doctor Login</a></li>
          {% endif %}</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

prometeo/altmed/templates/headache.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
      <div class="jumbotron">
        <h2>
          Suggested Alternatives are:
        </h2>
        {% for i in medicine%}
        <h3>{{ i }}</h3>
        {% endfor %}
      </div>
      {% if user.is_authenticated %}

        <h2>Enter Alternative here :</h2><form method="post" action="{% url 'core:headache' %}">
          {% csrf_token %}
          <label for="username">Enter Medicine: </label>
          <input type="text" name="add" placeholder="add medicine">

          <input type="submit" name="" value="submit">

        </form>

      {% endif %}
  </div>
{% endblock %}

prometeo/altmed/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
<style media="screen">
.dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropbtn:hover, .dropbtn:focus {
  background-color: #3e8e41;
}

#myInput {
  box-sizing: border-box;
  background-image: url('searchicon.png');
  background-position: 14px 12px;
  background-repeat: no-repeat;
  font-size: 16px;
  padding: 14px 20px 12px 45px;
  border: none;
  border-bottom: 1px solid #ddd;
}

#myInput:focus {outline: 3px solid #ddd;}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f6f6f6;
  min-width: 230px;
  overflow: auto;
  border: 1px solid #ddd;
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.row {
  display: flex;
  flex-wrap: wrap;
  padding: 0 4px;
}

/* Create two equal columns that sits next to each other */
.column {
  flex: 50%;
  padding: 0 4px;
}

.column1 {
  flex: 50%;
  height: 100px;
  width:500px;
  padding: 0 4px;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}

</style>
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the AntiMeds !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Get Alternatives for your medicines</h2>
    {% endif %}
  </div>
    <h4>
      <p>
      Our solution is to create a blockchain network where highly professional doctors post
     the alternatives for medicine
    </p>
    </h4>
    <div align="center">
  <h2>Search/Filter Dropdown</h2>
  <hr color="#000000">
  <p>Select medicines according to Diseases</p>
</div>
<style media="screen">
.dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropbtn:hover, .dropbtn:focus {
  background-color: #3e8e41;
}

#myInput {
  box-sizing: border-box;
  background-image: url('searchicon.png');
  background-position: 14px 12px;
  background-repeat: no-repeat;
  font-size: 16px;
  padding: 14px 20px 12px 45px;
  border: none;
  border-bottom: 1px solid #ddd;
}

#myInput:focus {outline: 3px solid #ddd;}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f6f6f6;
  min-width: 230px;
  overflow: auto;
  border: 1px solid #ddd;
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}

</style>
<div align="center">
  <div class="dropdown">
    <button onclick="myFunction()" class="dropbtn">Search Your Category</button>
    <div id="myDropdown" class="dropdown-content">
      <input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
      <a href="{% url 'core:headache' %}">Headache</a>
      <a href="{% url 'core:malaria'%}">Malaria</a>
      <a href="#blog">Dengue</a>
      <a href="#contact">Stomach Ache</a>

    </div>
  </div>
</div>
  <script>
  /* When the user clicks on the button,
  toggle between hiding and showing the dropdown content */
  function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
  }

  function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    div = document.getElementById("myDropdown");
    a = div.getElementsByTagName("a");
    for (i = 0; i < a.length; i++) {
      txtValue = a[i].textContent || a[i].innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        a[i].style.display = "";
      } else {
        a[i].style.display = "none";
      }
    }
  }
  </script>




</div>
{% endblock %}

prometeo/altmed/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1><form method="post" action="{% url 'core:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username"><label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password"><input type="submit" name="" value="Login"></form></div>
  </div>
{% endblock %}

prometeo/altmed/templates/malaria.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
      <div class="jumbotron">
        <h1>
          Suggested Alternatives are:
        </h1>
        {% for i in medicine%}
        <h2>{{ i }}</h2>
        {% endfor %}
      </div>
      {% if user.is_authenticated %}

        <h1>Enter Medicine here:</h1><form method="post" action="{% url 'core:user_login' %}">
          {% csrf_token %}
          <label for="username">Enter Medicine: </label>
          <input type="text" name="add" placeholder="add medicine">

          <input type="submit" name="" value="submit">

        </form>

      {% endif %}
  </div>
{% endblock %}

prometeo/altmed/templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
        <a href="{% url 'index' %}">Go to home page</a>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}